// ui/src/components/dialogs/ManageUsersDialog.vue
<template>
    <div v-if="shareSessionButtonIsVisible">
        <div style="padding: 0px">
            <el-badge
                :value="allowedUserProfiles.length === 0 ? undefined : allowedUserProfiles.length"
                style="width: 135px"
            >
                <el-button class="share-session-button" type="default" @click="handleOpen"> Share session </el-button>
            </el-badge>
        </div>
        <el-dialog
            v-model="dialogIsVisible"
            :append-to-body="true"
            title="Share session with other users"
            :before-close="handleClose"
        >
            <div style="width: 100%">
                <h3 style="margin-bottom: 0">Sharing with</h3>
                <p style="color: rgb(167, 167, 167)">The following users have access to this session</p>
                <div>
                    <p v-if="allowedUserProfiles.length === 0" style="color: rgb(217 190 46)">No users added</p>
                    <div v-else>
                        <el-tag
                            v-for="allowedUser in allowedUserProfiles"
                            :key="allowedUser?.sub"
                            style="margin: 4px"
                            size="large"
                            closable
                            @close="handleRemoveProfile(allowedUser?.sub)"
                        >
                            {{ allowedUser?.fullname || '' }} {{ `<${allowedUser?.email}>` }}
                        </el-tag>
                    </div>
                </div>
                <h3 style="margin-bottom: 0">Find users</h3>
                <p style="margin-top: 10px; color: rgb(167, 167, 167)">
                    Use the dropdown to search for other brainlife users
                </p>
                <el-autocomplete
                    v-model="userInput"
                    placeholder="start typing to see results"
                    :fetch-suggestions="handleFetchSuggestions"
                    :trigger-on-focus="false"
                    style="width: 100%"
                    clearable
                    :value-key="'fullname'"
                    @select="handleSelectProfile"
                >
                    <template #default="{ item }">
                        <div>
                            <p style="margin: 0">{{ item.fullname }} {{ `<${item.email}>` }}</p>
                        </div>
                    </template>
                    <template #suffix>
                        <el-container v-loading="isLoading" class="autocomplete-loader"> </el-container>
                    </template>
                </el-autocomplete>
            </div>
            <template #footer>
                <el-button type="danger" @click="handleClose">Close Dialog</el-button>
            </template>
        </el-dialog>
    </div>
</template>

<script lang="ts">
interface Profile {
    active?: boolean;
    email?: string;
    fullname?: string;
    profile?: {
        public: {
            bio?: string;
            institution?: string;
        };
    };
    sub?: number;
    username?: string;
    _id: string;
}

import { defineComponent } from 'vue';
import { mapActions, mapState } from 'vuex';
import axios from '../../axios.instance';
import jwtDecode from 'jwt-decode';
import { ElNotification } from 'element-plus';
import { retrieveJWT } from '../../lib';

export default defineComponent({
    data() {
        return {
            dialogIsVisible: false,
            profiles: [] as Profile[],
            userInput: '',
            isLoading: false,
        };
    },
    computed: {
        ...mapState(['session', 'config']),
        ...mapActions(['updateSessionAllowedUsers']),
        allowedUserProfiles() {
            const allowedUserList: number[] = this.session?.allowedUsers || [];
            return allowedUserList.map((allowedUserSub) =>
                this.profiles.find((profile) => profile.sub === allowedUserSub)
            );
        },
        shareSessionButtonIsVisible() {
            if (!this.session) return false;

            const jwt = retrieveJWT();
            if (!jwt) return false;

            const decoded: { sub: Partial<Profile> } = jwtDecode(jwt);
            if (!decoded?.sub) return false;

            return decoded.sub === this.session.ownerId;
        },
    },
    methods: {
        handleOpen() {
            this.dialogIsVisible = true;

            if (this.profiles.length > 0) return;

            this.isLoading = true;

            // TODO this should not be cached, we should only show the user once the full email has been typed (for privacy)
            axios
                .get<{ count: number; profiles: Profile[] }>(`${this.config.authhost}/profile/list?limit=6000`)
                .then((res) => {
                    this.profiles = res?.data?.profiles ? [...res.data.profiles] : [];
                })
                .catch((e) => {
                    console.error(e);
                })
                .finally(() => {
                    this.isLoading = false;
                });
        },
        handleClose() {
            this.dialogIsVisible = false;
        },
        handleSelectProfile(profile: Profile) {
            if (!this.session || !this.session.allowedUsers) return;
            if (!profile?.sub || !profile?.email) return;

            this.userInput = '';
            const updatedUsers: number[] = [...this.session.allowedUsers, profile.sub];
            this.isLoading = true;

            axios
                .patch(`${this.config.apihost}/session/${this.session._id}`, {
                    allowedUsers: updatedUsers,
                })
                .then((res) => {
                    this.$store.commit('updateSessionAllowedUsers', updatedUsers);
                })
                .catch((err) => {
                    console.error(err);
                    ElNotification({
                        title: 'There was an error sharing the session with other users',
                        type: 'error',
                    });
                })
                .finally(() => {
                    this.isLoading = false;
                });
        },
        handleRemoveProfile(allowedUserSub?: number) {
            if (!allowedUserSub || !this.session?.allowedUsers) return;

            const updatedUsers: number[] = [
                ...this.session.allowedUsers.filter((user: number) => user !== allowedUserSub),
            ];
            this.isLoading = true;

            axios
                .patch(`${this.config.apihost}/session/${this.session._id}`, {
                    allowedUsers: updatedUsers,
                })
                .then((res) => {
                    this.$store.commit('updateSessionAllowedUsers', updatedUsers);
                })
                .catch((err) => {
                    console.error(err);
                    ElNotification({
                        title: 'There was an error removing the user from the session',
                        type: 'error',
                    });
                })
                .finally(() => {
                    this.isLoading = false;
                });
        },
        handleFetchSuggestions(queryString: string | undefined, cb: any) {
            if (!queryString) {
                cb([]);
                return;
            }
            const transformedQuery = queryString.toLocaleLowerCase();

            const results = this.profiles.filter((profile: Profile) => {
                const lowercaseEmail = (profile?.email || '').toLocaleLowerCase();
                const lowerCaseFullname = (profile?.fullname || '').toLocaleLowerCase();
                return lowercaseEmail.includes(transformedQuery) || lowerCaseFullname.includes(transformedQuery);
            });

            const alreadySharedWithList: number[] = [this.session?.ownerId, ...(this.session?.allowedUsers || [])];
            cb(results.filter((result) => (result?.sub ? !alreadySharedWithList.includes(result.sub) : false)));
            return;
        },
    },
});
</script>

<style lang="scss">
.muted {
    color: gray;
}

.autocomplete-loader {
    width: 40px;
    height: 40px;
    .el-loading-mask {
        background-color: transparent !important;
    }
    svg {
        width: 30px !important;
    }
}

.share-session-button {
    display: flex;
    justify-content: center;
    width: 100%;
    margin-bottom: 10px;
    font-family: Merriweather Sans;
}
</style>

// ui/src/components/dialogs/ManageUsersDialog.tsx
import { useState, useMemo } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Cross2Icon } from '@radix-ui/react-icons';
import toast from 'react-hot-toast';
import { jwtDecode } from 'jwt-decode';

import { useAppSelector, useAppDispatch } from '../../store/hooks';
import { updateAllowedUsers } from '../../store/slices/sessionSlice';
import { retrieveJWT } from '../../lib';
import axios from '../../axios.instance';

interface Profile {
    active?: boolean;
    email?: string;
    fullname?: string;
    profile?: { public: { bio?: string; institution?: string } };
    sub?: number;
    username?: string;
    _id: string;
}

export default function ManageUsersDialog() {
    const dispatch = useAppDispatch();
    const session = useAppSelector((s) => s.session.data);
    const config = useAppSelector((s) => s.session.config);

    const [open, setOpen] = useState(false);
    const [profiles, setProfiles] = useState<Profile[]>([]);
    const [userInput, setUserInput] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [suggestions, setSuggestions] = useState<Profile[]>([]);

    // Only show if user is the session owner
    const isVisible = useMemo(() => {
        if (!session) return false;
        const jwt = retrieveJWT();
        if (!jwt) return false;
        try {
            const decoded: { sub: number } = jwtDecode(jwt);
            return decoded?.sub === session.ownerId;
        } catch {
            return false;
        }
    }, [session]);

    const allowedUserProfiles = useMemo(() => {
        const list = session?.allowedUsers || [];
        return list.map((sub) => profiles.find((p) => p.sub === sub)).filter(Boolean) as Profile[];
    }, [session?.allowedUsers, profiles]);

    if (!isVisible) return null;

    const handleOpen = () => {
        setOpen(true);
        if (profiles.length > 0) return;
        setIsLoading(true);
        axios
            .get<{ count: number; profiles: Profile[] }>(`${config.authhost}/profile/list?limit=6000`)
            .then((res) => {
                setProfiles(res?.data?.profiles ? [...res.data.profiles] : []);
            })
            .catch(console.error)
            .finally(() => setIsLoading(false));
    };

    const handleSearch = (query: string) => {
        setUserInput(query);
        if (!query) {
            setSuggestions([]);
            return;
        }
        const q = query.toLowerCase();
        const alreadyShared = [session?.ownerId, ...(session?.allowedUsers || [])];
        const results = profiles
            .filter((p) => {
                const email = (p.email || '').toLowerCase();
                const name = (p.fullname || '').toLowerCase();
                return email.includes(q) || name.includes(q);
            })
            .filter((p) => p.sub && !alreadyShared.includes(p.sub))
            .slice(0, 20);
        setSuggestions(results);
    };

    const handleSelect = (profile: Profile) => {
        if (!session || !profile.sub) return;
        setUserInput('');
        setSuggestions([]);
        const updatedUsers = [...(session.allowedUsers || []), profile.sub];
        setIsLoading(true);
        axios
            .patch(`${config.apihost}/session/${session._id}`, { allowedUsers: updatedUsers })
            .then(() => dispatch(updateAllowedUsers(updatedUsers)))
            .catch(() => toast.error('Error sharing session'))
            .finally(() => setIsLoading(false));
    };

    const handleRemove = (sub: number) => {
        if (!session) return;
        const updatedUsers = (session.allowedUsers || []).filter((u) => u !== sub);
        setIsLoading(true);
        axios
            .patch(`${config.apihost}/session/${session._id}`, { allowedUsers: updatedUsers })
            .then(() => dispatch(updateAllowedUsers(updatedUsers)))
            .catch(() => toast.error('Error removing user'))
            .finally(() => setIsLoading(false));
    };

    return (
        <div className="px-2.5">
            <div className="relative w-[135px]">
                <button
                    className="w-full py-1.5 mb-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded text-sm"
                    onClick={handleOpen}
                >
                    Share session
                </button>
                {allowedUserProfiles.length > 0 && (
                    <span className="absolute -top-1.5 -right-1.5 bg-red-500 text-white text-xs w-5 h-5 rounded-full flex items-center justify-center">
                        {allowedUserProfiles.length}
                    </span>
                )}
            </div>

            <Dialog.Root open={open} onOpenChange={setOpen}>
                <Dialog.Portal>
                    <Dialog.Overlay className="fixed inset-0 bg-black/40" />
                    <Dialog.Content className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-white rounded-lg shadow-xl w-[500px] max-h-[85vh] overflow-auto p-6">
                        <Dialog.Title className="text-lg font-semibold mb-4">
                            Share session with other users
                        </Dialog.Title>
                        <Dialog.Close className="absolute top-4 right-4">
                            <Cross2Icon />
                        </Dialog.Close>

                        <h3 className="font-semibold mb-0">Sharing with</h3>
                        <p className="text-gray-400 text-sm mb-3">The following users have access to this session</p>

                        {allowedUserProfiles.length === 0 ? (
                            <p className="text-yellow-600 text-sm">No users added</p>
                        ) : (
                            <div className="flex flex-wrap gap-1 mb-4">
                                {allowedUserProfiles.map((user) => (
                                    <span
                                        key={user.sub}
                                        className="inline-flex items-center gap-1 bg-gray-100 border border-gray-200 rounded px-2 py-1 text-sm"
                                    >
                                        {user.fullname || ''} &lt;{user.email}&gt;
                                        <button
                                            className="text-gray-400 hover:text-red-500 ml-1"
                                            onClick={() => user.sub && handleRemove(user.sub)}
                                        >
                                            ×
                                        </button>
                                    </span>
                                ))}
                            </div>
                        )}

                        <h3 className="font-semibold mb-0 mt-4">Find users</h3>
                        <p className="text-gray-400 text-sm mt-1 mb-2">
                            Use the dropdown to search for other brainlife users
                        </p>

                        <div className="relative">
                            <input
                                type="text"
                                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                                placeholder="Start typing to see results"
                                value={userInput}
                                onChange={(e) => handleSearch(e.target.value)}
                            />
                            {isLoading && (
                                <span className="absolute right-3 top-2.5 text-gray-400 text-sm animate-spin">⟳</span>
                            )}
                            {suggestions.length > 0 && (
                                <div className="absolute z-10 top-full left-0 right-0 bg-white border border-gray-200 rounded-b shadow-lg max-h-48 overflow-auto">
                                    {suggestions.map((p) => (
                                        <div
                                            key={p._id}
                                            className="px-3 py-2 hover:bg-blue-50 cursor-pointer text-sm"
                                            onClick={() => handleSelect(p)}
                                        >
                                            {p.fullname} &lt;{p.email}&gt;
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>

                        <div className="mt-6 flex justify-end">
                            <button
                                className="px-4 py-2 bg-red-500 hover:bg-red-600 text-white rounded text-sm"
                                onClick={() => setOpen(false)}
                            >
                                Close Dialog
                            </button>
                        </div>
                    </Dialog.Content>
                </Dialog.Portal>
            </Dialog.Root>
        </div>
    );
}
