// ui/src/pages/convert/Subject.tsx
import { forwardRef, useCallback, useEffect, useImperativeHandle, useState } from 'react';
import { useAppSelector, useAppDispatch } from '../../store/hooks';
import { updateEzbids, type Subject as SubjectType, type Session } from '../../store/slices/ezbidsSlice';

interface SubjectHandle {
    isValid: (cb: (err?: string) => void) => void;
}

const Subject = forwardRef<SubjectHandle>(function Subject(_props, ref) {
    const ezbids = useAppSelector((s) => s.ezbids.data);
    const [, forceUpdate] = useState(0);

    const validate = useCallback((s: SubjectType) => {
        s.validationErrors = [];
        if (s.subject.length === 0) {
            s.validationErrors.push('subject is a required field');
        }
        const cleansub = s.subject.replace(/[^0-9a-zA-Z]/g, '');
        if (s.subject !== cleansub) {
            s.validationErrors.push('subject contains non alphanumeric characters');
        }
    }, []);

    const validateAll = useCallback(() => {
        ezbids.subjects.forEach(validate);
    }, [ezbids.subjects, validate]);

    useEffect(() => {
        console.log('Subject create');
        validateAll();
        forceUpdate((n) => n + 1);
    }, []);

    useImperativeHandle(
        ref,
        () => ({
            isValid(cb: (err?: string) => void) {
                validateAll();
                let err: string | undefined;
                ezbids.subjects.forEach((s: SubjectType) => {
                    if (s.validationErrors.length > 0) err = 'Please correct all issues';
                });
                forceUpdate((n) => n + 1);
                return cb(err);
            },
        }),
        [ezbids.subjects, validateAll]
    );

    const [dropdownOpen, setDropdownOpen] = useState(false);

    const resetSubjects = useCallback(
        (command: string) => {
            console.log('resetting subjects');
            let sub = 1;
            switch (command) {
                case 'num':
                    ezbids.subjects.forEach((s: SubjectType) => {
                        s.subject = sub.toString().padStart(2, '0');
                        sub++;
                    });
                    break;
                case 'pid':
                    ezbids.subjects.forEach((s: SubjectType) => {
                        const firstInfo = s.PatientInfo[0];
                        s.subject = firstInfo.PatientID.replace(/[^0-9a-zA-Z]/g, '');
                    });
                    break;
                case 'pname':
                    ezbids.subjects.forEach((s: SubjectType) => {
                        const firstInfo = s.PatientInfo[0];
                        s.subject = firstInfo.PatientName.replace(/[^0-9a-zA-Z]/g, '');
                    });
                    break;
            }
            validateAll();
            setDropdownOpen(false);
            forceUpdate((n) => n + 1);
        },
        [ezbids.subjects, validateAll]
    );

    const handleSubjectChange = useCallback(
        (subject: SubjectType, value: string) => {
            subject.subject = value.trim();
            validate(subject);
            forceUpdate((n) => n + 1);
        },
        [validate]
    );

    const handleSessionChange = useCallback(
        (subject: SubjectType, session: Session, value: string) => {
            session.session = value.trim();
            validate(subject);
            forceUpdate((n) => n + 1);
        },
        [validate]
    );

    const handleExcludeSubject = useCallback((subject: SubjectType, checked: boolean) => {
        subject.exclude = checked;
        forceUpdate((n) => n + 1);
    }, []);

    const handleExcludeSession = useCallback((session: Session, checked: boolean) => {
        session.exclude = checked;
        forceUpdate((n) => n + 1);
    }, []);

    return (
        <div className="p-5">
            <p>
                Please map DICOM subject ID to BIDS subject ID. You can also specify session (AcquisitionDate) mappings
                for each subject, if appropriate. A mapping table can be downloaded at the end for future reference.
            </p>

            {/* Reset Subject Mapping Dropdown */}
            <div className="float-right m-2.5 relative">
                <button
                    className="px-3 py-1.5 bg-blue-500 hover:bg-blue-600 text-white text-sm rounded"
                    onClick={() => setDropdownOpen(!dropdownOpen)}
                >
                    Reset Subject Mapping <span className="ml-1">&#9662;</span>
                </button>
                {dropdownOpen && (
                    <ul className="absolute right-0 mt-1 bg-white border border-gray-200 rounded shadow-lg z-10 min-w-[180px] list-none p-0 m-0">
                        <li
                            className="px-4 py-2 hover:bg-gray-100 cursor-pointer text-sm"
                            onClick={() => resetSubjects('pname')}
                        >
                            Use PatientName
                        </li>
                        <li
                            className="px-4 py-2 hover:bg-gray-100 cursor-pointer text-sm"
                            onClick={() => resetSubjects('pid')}
                        >
                            Use PatientID
                        </li>
                        <li
                            className="px-4 py-2 hover:bg-gray-100 cursor-pointer text-sm"
                            onClick={() => resetSubjects('num')}
                        >
                            Numerical (1,2,3..)
                        </li>
                    </ul>
                )}
            </div>

            {/* Subjects Table */}
            <table className="w-full text-sm align-top border-collapse">
                <thead>
                    <tr className="bg-gray-50">
                        <th className="p-2 text-left w-[330px] border-b border-gray-200">DICOM Patient</th>
                        <th className="p-2 text-left border-b border-gray-200">Subject/Sessions Mappings</th>
                    </tr>
                </thead>
                <tbody>
                    {ezbids.subjects.map((subject, sIdx) => (
                        <tr key={sIdx} className="border-b border-gray-200 align-top">
                            {/* DICOM Patient Column */}
                            <td className="p-2 w-[330px]">
                                <span className="float-right text-xl font-bold">&rarr;</span>
                                <div>
                                    {subject.PatientInfo.map((info, infoIdx) => (
                                        <p
                                            key={infoIdx}
                                            className={`mt-0 mb-1 ${infoIdx > 0 ? 'border-t border-black/5 pt-1' : ''}`}
                                        >
                                            <b>PatientID</b> {info.PatientID}
                                            <br />
                                            <b>PatientName</b> {info.PatientName}
                                            <br />
                                            <b>PatientBirthDate</b> {info.PatientBirthDate || '(not set)'}
                                            <br />
                                            <b>Directory</b> {(info as any).file_directory}
                                            <br />
                                        </p>
                                    ))}
                                </div>
                            </td>

                            {/* Subject/Sessions Mappings Column */}
                            <td className="p-2">
                                <label className="flex items-center gap-1 mb-2 cursor-pointer">
                                    <input
                                        type="checkbox"
                                        checked={subject.exclude}
                                        onChange={(e) => handleExcludeSubject(subject, e.target.checked)}
                                        title="Exclude all objects from BIDS output for this subject"
                                    />
                                    Exclude this subject
                                </label>

                                <div className="flex items-center mb-2">
                                    <span className="bg-gray-100 border border-gray-300 border-r-0 px-2 py-1 text-sm rounded-l">
                                        sub-
                                    </span>
                                    <input
                                        type="text"
                                        className="border border-gray-300 px-2 py-1 text-sm rounded-r flex-1"
                                        value={subject.subject}
                                        onChange={(e) => handleSubjectChange(subject, e.target.value)}
                                    />
                                </div>

                                {/* Sessions Sub-Table */}
                                {subject.sessions.length > 0 && (
                                    <table className="w-full text-sm mb-2">
                                        <tbody>
                                            {subject.sessions.map((session, sesIdx) => (
                                                <tr key={sesIdx}>
                                                    <td className="p-1 w-1/3 align-top">
                                                        <b>AcquisitionDate</b>
                                                        <br />
                                                        {session.AcquisitionDate}
                                                    </td>
                                                    <td className="p-1 w-2/3">
                                                        <label className="flex items-center gap-1 mb-1 cursor-pointer">
                                                            <input
                                                                type="checkbox"
                                                                checked={session.exclude}
                                                                onChange={(e) =>
                                                                    handleExcludeSession(session, e.target.checked)
                                                                }
                                                                title="Exclude all objects for this session"
                                                            />
                                                            Exclude this session
                                                        </label>
                                                        <div className="flex items-center">
                                                            <span className="bg-gray-100 border border-gray-300 border-r-0 px-2 py-1 text-sm rounded-l">
                                                                ses-
                                                            </span>
                                                            <input
                                                                type="text"
                                                                className="border border-gray-300 px-2 py-1 text-sm rounded-r flex-1"
                                                                placeholder="no session"
                                                                value={session.session}
                                                                onChange={(e) =>
                                                                    handleSessionChange(
                                                                        subject,
                                                                        session,
                                                                        e.target.value
                                                                    )
                                                                }
                                                            />
                                                        </div>
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                )}

                                {/* Validation Errors */}
                                {subject.validationErrors.map((error, errIdx) => (
                                    <div
                                        key={errIdx}
                                        className="flex items-center gap-2 p-2 mb-1 bg-red-50 border border-red-200 rounded text-red-700 text-sm"
                                    >
                                        <span className="text-red-500">&#9888;</span>
                                        {error}
                                    </div>
                                ))}
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <pre className="mt-4 text-xs bg-gray-50 p-2 rounded overflow-auto">
                {JSON.stringify(ezbids.subjects, null, 2)}
            </pre>
        </div>
    );
});

export default Subject;

// ui/src/features/subject/Subject.vue
<template>
    <div class="subject-page">
        <header class="subject-intro">
            <h2 class="subject-intro__title">Subject mapping</h2>
            <p class="subject-intro__text">
                Please map DICOM subject IDs to BIDS subject IDs. You can also specify session
                (<strong>AcquisitionDate</strong>) mappings for each subject if needed. A mapping table can be
                downloaded at the end for future reference.
            </p>
        </header>

        <div class="subject-layout">
            <section class="subject-card subject-card--table">
                <div class="subject-card__toolbar">
                    <el-dropdown size="small" @command="resetSubjects">
                        <el-button type="primary" size="small">
                            Reset Subject Mapping <i class="el-icon-arrow-down el-icon--right"></i>
                        </el-button>
                        <template #dropdown>
                            <el-dropdown-menu>
                                <el-dropdown-item command="pname">Use PatientName</el-dropdown-item>
                                <el-dropdown-item command="pid">Use PatientID</el-dropdown-item>
                                <el-dropdown-item command="num">Numerical (1,2,3..)</el-dropdown-item>
                            </el-dropdown-menu>
                        </template>
                    </el-dropdown>
                </div>

                <div class="subject-table-wrap">
                    <el-table :data="ezbids.subjects" size="small" class="table-align-top subject-table">
                        <el-table-column label="DICOM Patient" min-width="160" width="180">
                            <template #default="scope">
                                <div class="patient-cell">
                                    <i class="el-icon-right patient-cell__arrow" />
                                    <div class="patient-info">
                                        <p v-for="(info, idx) in scope.row.PatientInfo" :key="idx">
                                            <b>PatientID</b> {{ info.PatientID }}<br />
                                            <b>PatientName</b> {{ info.PatientName }}<br />
                                            <b>PatientBirthDate</b> {{ info.PatientBirthDate || '(not set)' }}<br />
                                            <b>Directory</b> {{ info.file_directory }}<br />
                                        </p>
                                    </div>
                                </div>
                            </template>
                        </el-table-column>
                        <el-table-column label="BIDS subject" min-width="160">
                            <template #default="scope">
                                <div class="subject-cell">
                                    <div class="subject-cell__exclude">
                                        <el-checkbox
                                            v-model="scope.row.exclude"
                                            title="Exclude all objects from BIDS output for this subject"
                                        >
                                            Exclude this subject
                                        </el-checkbox>
                                    </div>
                                    <el-input
                                        v-model.trim="scope.row.subject"
                                        size="small"
                                        @change="validate(scope.row)"
                                    >
                                        <template #prepend>sub-</template>
                                    </el-input>
                                    <el-alert
                                        v-for="(error, idx) in scope.row.validationErrors"
                                        :key="idx"
                                        show-icon
                                        :closable="false"
                                        type="error"
                                        :title="error"
                                        class="mapping-error"
                                    />
                                </div>
                            </template>
                        </el-table-column>
                        <el-table-column label="Sessions" min-width="160">
                            <template #default="scope">
                                <div v-if="scope.row.sessions?.length" class="session-list">
                                    <div
                                        v-for="(session, sIdx) in scope.row.sessions"
                                        :key="`${session.AcquisitionDate}-${sIdx}`"
                                        class="session-item"
                                    >
                                        <div class="session-item__exclude">
                                            <el-checkbox
                                                v-model="session.exclude"
                                                title="Exclude all objects for this session"
                                                class="session-checkbox"
                                            >
                                                Exclude this session
                                            </el-checkbox>
                                        </div>
                                        <el-input
                                            v-model.trim="session.session"
                                            placeholder="no session"
                                            size="small"
                                            @change="validate(scope.row)"
                                        >
                                            <template #prepend>ses-</template>
                                        </el-input>
                                        <div class="session-item__date">
                                            AcquisitionDate: {{ session.AcquisitionDate }}
                                        </div>
                                    </div>
                                </div>
                                <span v-else class="session-list__empty">No sessions</span>
                            </template>
                        </el-table-column>
                    </el-table>
                </div>
            </section>

            <aside class="subject-card json-panel">
                <h3 class="json-panel__title">Subject mapping JSON</h3>
                <pre class="status">{{ ezbids.subjects }}</pre>
            </aside>
        </div>
    </div>
</template>

<script lang="ts">
import { mapState } from 'vuex';
import { defineComponent } from 'vue';
import { Subject } from '@/store/store.types';

export default defineComponent({
    data() {
        return {};
    },
    /*
    watch: {
        '$root.currentPage'(v) {
            if(v.id == 'subject') {
                this.$root.subjects.forEach(this.validate);
            }
        },
    },
    */
    computed: {
        ...mapState(['ezbids', 'config']),
    },

    created() {
        console.log('Subject create');
        this.validateAll();
    },

    methods: {
        resetSubjects(command: string) {
            console.log('resetting subjects');
            let sub = 1;
            switch (command) {
                case 'num':
                    this.ezbids.subjects.forEach((s: Subject) => {
                        s.subject = sub.toString().padStart(2, '0');
                        sub++;
                    });
                    break;
                case 'pid':
                    this.ezbids.subjects.forEach((s: Subject) => {
                        const firstInfo = s.PatientInfo[0]; //TODO - should I concatenate all PatientInfo?
                        s.subject = firstInfo.PatientID.replace(/[^0-9a-zA-Z]/g, '');
                    });
                    break;
                case 'pname':
                    this.ezbids.subjects.forEach((s: Subject) => {
                        const firstInfo = s.PatientInfo[0]; //TODO - should I concatenate all PatientInfo?
                        s.subject = firstInfo.PatientName.replace(/[^0-9a-zA-Z]/g, '');
                    });
                    break;
            }

            this.validateAll();
        },

        validateAll() {
            this.ezbids.subjects.forEach(this.validate);
        },

        validate(s: Subject) {
            //Vue.set(s, 'validationErrors', []);
            s.validationErrors = [];

            if (s.subject.length == 0) {
                //this.$store.commit("addValidationError", {s, error:"subject is a required field"});
                s.validationErrors.push('subject is a required field');
            }

            let cleansub = s.subject.replace(/[^0-9a-zA-Z]/g, '');
            if (s.subject != cleansub) {
                //this.$store.commit("addValidationError", {s, error: "subject contains non alphanumeric characters"});
                s.validationErrors.push('subject contains non alphanumeric characters');
            }
        },

        isValid(cb: (v?: string) => void) {
            this.validateAll();

            let err = undefined;
            this.ezbids.subjects.forEach((s: Subject) => {
                if (s.validationErrors.length > 0) err = 'Please correct all issues';
            });
            return cb(err);
        },
    },
});
</script>

<style lang="scss" scoped>
.subject-page {
    width: 100%;
    max-width: min(1680px, 100%);
    margin: 0 auto;
    padding: 0.5rem 1.25rem 2.75rem;
    box-sizing: border-box;
    overflow-x: hidden;
}

.subject-intro {
    margin-bottom: 1.5rem;
    padding: 1.35rem 1.5rem 1.5rem;
    border-radius: 10px;
    border: 1px solid var(--el-border-color-lighter, #ebeef5);
    background: var(--el-fill-color-blank, #fff);
    box-shadow: 0 1px 2px rgb(0 0 0 / 4%);
}

.subject-intro__title {
    margin: 0 0 0.65rem;
    font-size: 1.25rem;
    font-weight: 600;
    letter-spacing: -0.02em;
    color: var(--el-text-color-primary, #303133);
}

.subject-intro__text {
    margin: 0;
    font-size: 14px;
    line-height: 1.65;
    color: var(--el-text-color-regular, #606266);
}

.subject-layout {
    display: grid;
    grid-template-columns: 1fr;
    gap: 1rem;
    align-items: start;
    min-width: 0;
}

@media (min-width: 1500px) {
    .subject-layout {
        grid-template-columns: minmax(0, 3fr) minmax(360px, 2fr);
    }
}

.subject-card {
    min-width: 0;
    padding: 1.25rem;
    border-radius: 12px;
    border: 1px solid var(--el-border-color-lighter, #ebeef5);
    background: var(--el-bg-color, #fff);
}

.subject-card--table {
    overflow: hidden;
}

.subject-table-wrap {
    width: 100%;
    max-width: 100%;
    overflow-x: auto;
}

.subject-card__toolbar {
    display: flex;
    justify-content: flex-end;
    margin-bottom: 0.9rem;
}

.subject-table {
    width: 100%;
}

.patient-cell {
    display: flex;
    align-items: flex-start;
    vertical-align: top;
}

.patient-cell__arrow {
    margin-top: 2px;
    font-size: 1rem;
    font-weight: 700;
    color: var(--el-text-color-secondary, #909399);
}

.patient-info {
    overflow-wrap: anywhere;
    padding: 0px;
    vertical-align: top;

    p {
        margin-top: 0;
        margin-bottom: 5px;
        line-height: 1.4;
    }

    p:not(:first-child) {
        border-top: 1px solid var(--el-border-color-extra-light, #f2f6fc);
        padding-top: 5px;
    }
}

:deep(.el-checkbox__label) {
    font-size: 12px !important;
}

:deep(.el-checkbox) {
    height: 20px !important;
}

.subject-cell {
    display: flex;
    flex-direction: column;
    gap: 4px;
    vertical-align: top;
}

.subject-cell__exclude {
    line-height: normal;
}

.mapping-error {
    margin-top: 4px;
    margin-bottom: 0;
}

.session-list {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
}

.session-list__empty {
    font-size: 12px;
    color: var(--el-text-color-placeholder, #c0c4cc);
}

.session-item {
    display: flex;
    flex-direction: column;
    gap: 4px;
    padding-bottom: 0.75rem;
}

.session-item:last-child {
    padding-bottom: 0;
    border-bottom: none;
}

.session-item__date {
    margin: 4px 0;
    font-size: 12px;
    line-height: 1.35;
    overflow-wrap: anywhere;
}

.session-item__exclude {
    line-height: normal;
}

:deep(.subject-table .el-table__body tr:hover > td.el-table__cell) {
    background-color: transparent !important;
}

:deep(td.el-table__cell) {
    vertical-align: top;
}

.json-panel {
    position: static;
    max-height: none;
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

.json-panel__title {
    margin: 0 0 0.75rem;
    font-size: 0.95rem;
    font-weight: 600;
    color: var(--el-text-color-regular, #606266);
}

.json-panel pre.status {
    max-height: 320px;
    min-height: 200px;
}

pre.status {
    flex: 1;
    margin: 0;
    padding: 10px;
    border-radius: 5px;
    background-color: #666;
    color: #fff;
    overflow: auto;
    word-break: break-all;
    min-height: 320px;
}

el-table {
    border-color: transparent !important;
}

@media (min-width: 1500px) {
    .json-panel {
        position: sticky;
        top: 16px;
        max-height: calc(80vh);
    }

    .json-panel pre.status {
        max-height: none;
        min-height: 320px;
    }
}
</style>
