// ui/src/pages/convert/Participant.tsx
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useState } from 'react';
import { useAppSelector } from '../../store/hooks';
import type { OrganizedSubject } from '../../store/slices/ezbidsSlice';

interface ParticipantHandle {
    isValid: (cb: (err?: string) => void) => void;
}

const Participant = forwardRef<ParticipantHandle>(function Participant(_props, ref) {
    const ezbids = useAppSelector((s) => s.ezbids.data);
    const [newcolumn, setNewcolumn] = useState('');
    const [, forceUpdate] = useState(0);

    // Initialize participantsInfo for each organized subject
    useEffect(() => {
        ezbids._organized.forEach((o: OrganizedSubject) => {
            if (!ezbids.participantsInfo[o.subject_idx]) {
                ezbids.participantsInfo[o.subject_idx] = {};
            }
        });
    }, []);

    useImperativeHandle(
        ref,
        () => ({
            isValid(cb: (err?: string) => void) {
                console.log('todo - validate participant');
                cb();
            },
        }),
        []
    );

    // Only show subjects that are really used (not excluded)
    const finalSubs = useMemo(() => {
        const result: number[] = [];
        ezbids._organized.forEach((sub: OrganizedSubject) => {
            let use = false;
            sub.sess.forEach((ses) => {
                if (ses.objects.some((o) => !o._exclude)) use = true;
            });
            if (use) result.push(sub.subject_idx);
        });
        return result;
    }, [ezbids._organized]);

    const addNewColumn = useCallback(() => {
        if (!newcolumn) return;
        if (ezbids.participantsColumn && ezbids.participantsColumn[newcolumn]) return;
        ezbids.participantsColumn[newcolumn] = {
            Description: '',
            Units: '',
            Levels: {},
        };
        setNewcolumn('');
        forceUpdate((n) => n + 1);
    }, [newcolumn, ezbids.participantsColumn]);

    const removeColumn = useCallback(
        (key: string) => {
            delete ezbids.participantsColumn[key];
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsColumn]
    );

    const handleColumnDescriptionChange = useCallback(
        (key: string, value: string) => {
            ezbids.participantsColumn[key].Description = value;
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsColumn]
    );

    const handleColumnUnitsChange = useCallback(
        (key: string, value: string) => {
            ezbids.participantsColumn[key].Units = value;
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsColumn]
    );

    const handleParticipantInfoChange = useCallback(
        (subjectIdx: number, key: string, value: string) => {
            if (!ezbids.participantsInfo[subjectIdx]) {
                ezbids.participantsInfo[subjectIdx] = {};
            }
            ezbids.participantsInfo[subjectIdx][key] = value.trim();
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsInfo]
    );

    const columnKeys = Object.keys(ezbids.participantsColumn || {});

    return (
        <div className="p-5">
            <p>You can store metadata/phenotypical data for each participant in this dataset.</p>
            <p>Please skip this step if you do not wish to store any phenotypical data.</p>

            <h5 className="text-base font-semibold mt-4">Phenotype Columns</h5>
            <small className="text-gray-500">Define phenotypical keys stored for this study (recommended).</small>
            <br />
            <br />

            <div className="flex flex-wrap gap-2.5">
                {/* Column Editors */}
                {columnKeys.map((key) => {
                    const column = ezbids.participantsColumn[key];
                    return (
                        <div key={key} className="bg-gray-50 mb-2.5 p-4 rounded w-[300px] text-center">
                            <span className="float-right">
                                <button
                                    className="px-2 py-0.5 bg-red-500 hover:bg-red-600 text-white text-xs rounded"
                                    onClick={() => removeColumn(key)}
                                >
                                    &#10005;
                                </button>
                            </span>
                            <b>{key}</b>
                            <br />
                            <br className="clear-both" />

                            <div className="mb-2 text-left">
                                <label className="block text-sm text-gray-600 mb-1">Description</label>
                                <textarea
                                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    placeholder="Description"
                                    value={column.Description || ''}
                                    onChange={(e) => handleColumnDescriptionChange(key, e.target.value)}
                                />
                            </div>

                            <div className="mb-2 text-left">
                                <label className="block text-sm text-gray-600 mb-1">Units</label>
                                <input
                                    type="text"
                                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    placeholder="Units"
                                    value={column.Units || ''}
                                    onChange={(e) => handleColumnUnitsChange(key, e.target.value)}
                                />
                            </div>

                            <div className="mb-2 text-left">
                                <label className="block text-sm text-gray-600 mb-1">Levels</label>
                                <small className="text-gray-400">TODO.. (levels)</small>
                            </div>
                        </div>
                    );
                })}

                {/* Add New Column */}
                <div className="bg-gray-50 p-4 rounded w-[200px] text-center">
                    <div className="flex">
                        <input
                            type="text"
                            className="border border-gray-300 rounded-l px-2 py-1 text-sm flex-1 min-w-0"
                            placeholder="Add New Column"
                            value={newcolumn}
                            onChange={(e) => setNewcolumn(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === 'Enter') addNewColumn();
                            }}
                        />
                        <button
                            className="px-3 py-1 bg-blue-500 hover:bg-blue-600 text-white text-sm rounded-r"
                            onClick={addNewColumn}
                        >
                            Add
                        </button>
                    </div>
                    <div className="mt-2">
                        <a
                            href="https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file"
                            target="_blank"
                            rel="noreferrer"
                            className="text-blue-500 text-sm"
                        >
                            See here for suggestions
                        </a>
                    </div>
                </div>
            </div>

            <br className="clear-both" />

            <h5 className="text-base font-semibold mt-4">participants.tsv</h5>
            <small className="text-gray-500">Enter phenotypical data associated with each participant.</small>
            <br />
            <br />

            <div className="w-full overflow-x-auto">
                <table className="w-full border-collapse text-[90%]">
                    <thead className="bg-gray-100 text-gray-600">
                        <tr>
                            <th className="p-1.5 px-2.5 text-left">participant_id</th>
                            {columnKeys.map((key) => (
                                <th key={key} className="p-1.5 px-2.5 text-left">
                                    {key}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {finalSubs.map((subjectIdx) => (
                            <tr key={subjectIdx}>
                                <th className="p-1.5 px-2.5 text-left font-normal">
                                    sub-{ezbids.subjects[subjectIdx]?.subject}
                                </th>
                                {columnKeys.map((key) => (
                                    <td key={key} className="p-1.5 px-2.5">
                                        <input
                                            type="text"
                                            className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                            value={ezbids.participantsInfo[subjectIdx]?.[key] || ''}
                                            onChange={(e) =>
                                                handleParticipantInfoChange(subjectIdx, key, e.target.value)
                                            }
                                        />
                                    </td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
});

export default Participant;

// ui/src/features/participant/Participant.vue
<template>
    <div class="participant-page">
        <header class="participant-intro">
            <h2 class="participant-intro__title">Participant Metadata</h2>
            <p class="participant-intro__text">
                You can store metadata and phenotypical data for each participant in this dataset.
            </p>
            <p class="participant-intro__text">
                Skip this step if you do not wish to include participant-level phenotypical information.
            </p>
        </header>

        <section class="participant-card">
            <div style="display: flex; justify-content: space-between; align-items: flex-start">
                <div class="section-head">
                    <h3 class="section-title">Phenotype Columns</h3>
                    <small class="section-subtitle"
                        >Define phenotypical keys stored for this study (recommended).</small
                    >
                </div>
                <div>
                    <div style="margin-bottom: 4px">
                        <el-input v-model="newcolumn" placeholder="Add New Column" size="mini">
                            <template #append>
                                <el-button type="primary" @click="addNewColumn">Add</el-button>
                            </template>
                        </el-input>
                    </div>
                    <a
                        class="column-editor__link"
                        href="https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file"
                        target="_blank"
                    >
                        See BIDS suggestions
                    </a>
                </div>
            </div>

            <el-form label-width="92px" class="column-editor-form">
                <div class="column-grid">
                    <div v-for="(column, idx) in ezbids.participantsColumn" :key="idx" class="column-editor">
                        <div class="column-editor__head">
                            <b>{{ idx }}</b>
                            <el-button type="danger" size="mini" @click="remove(idx)">
                                <Remove style="width: 16px" />
                            </el-button>
                        </div>
                        <el-form-item label="Description">
                            <el-input
                                v-model="column.Description"
                                type="textarea"
                                placeholder="Description"
                                size="mini"
                            />
                        </el-form-item>
                        <el-form-item label="Units">
                            <el-input v-model="column.Units" placeholder="Units" size="mini" />
                        </el-form-item>
                        <!-- <el-form-item label="Levels">
                            <small>TODO.. (levels)</small>
                        </el-form-item> -->
                    </div>
                </div>
            </el-form>
        </section>

        <section class="participant-card">
            <div class="section-head">
                <h3 class="section-title">participants.tsv</h3>
                <small class="section-subtitle">Enter phenotypical data associated with each participant.</small>
            </div>

            <div class="table-wrap">
                <table class="phenotype">
                    <thead>
                        <tr>
                            <th>participant_id</th>
                            <th v-for="(column, key) in ezbids.participantsColumn" :key="key">
                                {{ key }}
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="subject_idx in finalSubs" :key="subject_idx">
                            <th>{{ 'sub-' + ezbids.subjects[subject_idx].subject }}</th>
                            <td v-for="(column, key) in ezbids.participantsColumn" :key="key">
                                <el-input v-model.trim="ezbids.participantsInfo[subject_idx][key]" size="mini" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</template>

<script lang="ts">
import { mapState } from 'vuex';
import { defineComponent } from 'vue';
// import { updateParticipantsInfo } from './libUnsafe';

//element-plus icons are bad .. replace it with fontawesome
// @ts-ignore
import { Remove } from '@element-plus/icons/lib';
import { OrganizedSubject } from '@/store/store.types';

export default defineComponent({
    components: {
        Remove,
    },

    data() {
        return {
            newcolumn: '',
        };
    },

    computed: {
        ...mapState(['ezbids', 'config']),
        //...mapGetters(['findSubjectFromString']),

        // //only show subjects that are really used (not excluded)
        // finalSubs() {
        //     let finalSubs: any = [];
        //     this.ezbids._organized.forEach((sub: OrganizedSubject) => {
        //         let use = false;
        //         sub.sess.forEach((ses) => {
        //             if (ses.objects.some((o) => !o._exclude)) use = true;
        //         });
        //         if (use) finalSubs.push({ subIdx: sub.subject_idx, subID: sub.sess[0].objects[0]._entities.subject });
        //     });
        //     console.log('finalSubs', finalSubs);
        //     return finalSubs;
        // },

        //only show subjects that are really used (not excluded)
        finalSubs() {
            let finalSubs = [] as number[];
            this.ezbids._organized.forEach((sub: OrganizedSubject) => {
                let use = false;
                sub.sess.forEach((ses) => {
                    if (ses.objects.some((o) => !o._exclude)) use = true;
                });
                if (use) finalSubs.push(sub.subject_idx);
            });
            return finalSubs;
        },
    },

    created() {
        //initialize
        // TODO: don't need this I think if we're updating participants Info due to user changes in UI.
        this.ezbids._organized.forEach((o: OrganizedSubject) => {
            if (!this.ezbids.participantsInfo[o.subject_idx]) this.ezbids.participantsInfo[o.subject_idx] = {};
        });
        // this.ezbids.participantsInfo = updateParticipantsInfo(this.ezbids);
    },

    methods: {
        addNewColumn() {
            if (!this.newcolumn) return;
            if (this.ezbids.participantsColumn && this.ezbids.participantsColumn[this.newcolumn]) return;

            this.ezbids.participantsColumn[this.newcolumn] = {
                Description: '',
                Units: '',
                Levels: {},
            };
            this.newcolumn = '';
        },

        remove(idx: string | number) {
            delete this.ezbids.participantsColumn[idx];
        },

        //TODO
        validate() {
            console.log('todo - validate participant');
        },

        // isValid(cb: (v?: string)=>void) {
        //     this.validate();
        //     cb();
        // }

        isValid(cb: (v?: string) => void) {
            this.validate();
            // let errors = validateParticipantsInfo(this.ezbids);
            // if (errors.length) {
            //     for (const e of errors) {
            //         return cb(e);
            //     }
            // }
            cb();
        },
    },
});
</script>

<style lang="scss" scoped>
.participant-page {
    max-width: 1400px;
    margin: 0 auto;
    padding: 0.5rem 1.25rem 2.75rem;
}

.participant-intro {
    margin-bottom: 1.5rem;
    padding: 1.35rem 1.5rem 1.5rem;
    border-radius: 10px;
    border: 1px solid var(--el-border-color-lighter, #ebeef5);
    background: var(--el-fill-color-blank, #fff);
    box-shadow: 0 1px 2px rgb(0 0 0 / 4%);
}

.participant-intro__title {
    margin: 0 0 0.65rem;
    font-size: 1.25rem;
    font-weight: 600;
    letter-spacing: -0.02em;
    color: var(--el-text-color-primary, #303133);
}

.participant-intro__text {
    margin: 0.45rem 0 0;
    font-size: 14px;
    line-height: 1.6;
    color: var(--el-text-color-regular, #606266);
}

.participant-card {
    padding: 1.1rem 1.25rem;
    border-radius: 12px;
    border: 1px solid var(--el-border-color-lighter, #ebeef5);
    background: var(--el-bg-color, #ffffff);
    margin-bottom: 1rem;
}

.section-head {
    margin-bottom: 2rem;
}

.section-title {
    margin: 0;
    font-size: 1rem;
    font-weight: 600;
}

.section-subtitle {
    display: block;
    margin-top: 0.35rem;
    color: var(--el-text-color-secondary, #909399);
}

.column-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 12px;
}

.column-editor {
    background: #ffffff;
    border: 1px solid var(--el-border-color-extra-light, #f2f6fc);
    border-radius: 8px;
    padding: 12px;
}

.column-editor__head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;
    padding: 0 4px;
}

.column-editor--add {
    display: flex;
    flex-direction: column;
    justify-content: center;
    gap: 8px;
    min-height: 180px;
    border: 2px solid lightblue;
}

.column-editor__link {
    font-size: 12px;
}

.column-editor-form :deep(.el-form-item) {
    margin-bottom: 8px;
}

.column-editor-form :deep(.el-form-item__label) {
    text-align: right;
    color: var(--el-text-color-secondary, #909399);
}

.column-editor-form :deep(.el-form-item__content) {
    min-width: 0;
}

.table-wrap {
    overflow-x: auto;
}

table.phenotype {
    width: 100%;
    border-collapse: collapse;
    font-size: 90%;
}
table.phenotype thead {
    background-color: #eee;
    color: #666;
}
table.phenotype td,
table.phenotype th {
    padding: 6px 10px;
    white-space: nowrap;
}
</style>
