// ui/src/NotFound.vue
<template>
    <el-container direction="vertical" class="container">
        <LandingPageHeader />
        <el-main style="color: white">
            <el-row style="height: 100%">
                <el-col :span="1"></el-col>
                <el-col
                    :span="22"
                    style="display: flex; align-items: center; justify-content: center; width: 100%; height: 100%"
                >
                    <div class="not-found-message">
                        <h1>Page Not found</h1>
                        <p>The page you are looking for does not exist.</p>
                    </div>
                </el-col>
                <el-col :span="1"></el-col>
            </el-row>
        </el-main>
        <LandingPageFooter />
    </el-container>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import LandingPageFooter from '@/features/landing/LandingPageFooter.vue';
import LandingPageHeader from '@/features/landing/LandingPageHeader.vue';

export default defineComponent({
    components: {
        LandingPageFooter: LandingPageFooter,
        LandingPageHeader: LandingPageHeader,
    },
});
</script>
<style>
.container {
    height: 100vh;
}

.not-found-message {
    background-color: #20ab5c;
    padding: 2rem;
    border-radius: 4px;
    font-size: var(--el-font-size-extra-large);
}

.background-stripe {
    transform: skewY(-12deg);
    height: 50vh;
}
</style>

// ui/src/pages/NotFound.tsx
import Header from '../components/landing/Header';
import Footer from '../components/landing/Footer';

export default function NotFound() {
    return (
        <div className="flex flex-col h-screen">
            <Header />
            <main className="flex-1 flex items-center justify-center text-white">
                <div className="flex">
                    <div className="w-[4%]" />
                    <div className="flex items-center justify-center w-full h-full">
                        <div className="bg-[#20ab5c] p-8 rounded text-xl">
                            <h1>Page Not found</h1>
                            <p>The page you are looking for does not exist.</p>
                        </div>
                    </div>
                    <div className="w-[4%]" />
                </div>
            </main>
            <Footer />
        </div>
    );
}
