// ui/src/components/ColumnSelecter.tsx
import React from 'react';

interface ColumnSelecterProps {
    value: string;
    onChange: (value: string) => void;
    columnKeys: string[];
    sampleValues: Record<string, string[]>;
}

const ColumnSelecter: React.FC<ColumnSelecterProps> = ({ value, onChange, columnKeys, sampleValues }) => {
    const composeSampleValue = (key: string) => {
        const samples = sampleValues[key].join(', ');
        if (samples.length > 30) return samples.substring(0, 30) + ' ...';
        return samples;
    };

    return (
        <select
            className="text-sm border border-gray-300 rounded px-2 py-1"
            value={value}
            onChange={(e) => onChange(e.target.value)}
        >
            <option value="">Select column</option>
            {columnKeys.map((key, idx) => (
                <option key={idx} value={key}>
                    {key} — {composeSampleValue(key)}
                </option>
            ))}
        </select>
    );
};

export default ColumnSelecter;

// ui/src/components/columnselecter.vue
<template>
<el-select v-model="modelValue" size="small" clearable placeholder="Select column">
    <el-option v-for="(key, idx) in columnKeys" :key="idx" :label="key" :value="key">
        <div style="display: inline-block; min-width: 100px">{{key}}</div>
        <small>{{composeSampleValue(key)}}</small>
    </el-option>
</el-select>
</template>

<script>

export default {
    props: [
        'modelValue', 'columnKeys', 'sampleValues',
    ],
    mounted() {
    },
    data() {
        return {
            //json: "{}",
        }
    },
    methods: {
        /*
        change(v) {
            this.$emit("update:modelValue", v);
        },
        */

        composeSampleValue(key) {
            const samples = this.sampleValues[key].join(', ');
            if(samples.length > 30) return samples.substring(0, 30)+" ...";
            return samples;
        },
     }
}


</script>
