// ui/src/components/ShowFile.tsx
import React, { useEffect, useState } from 'react';
// @ts-ignore
import Convert from 'ansi-to-html';
import axios from '../axios.instance';
import { useAppSelector } from '../store/hooks';

const convert = new Convert();

interface ShowFileProps {
    path: string;
    tall?: boolean;
}

const ShowFile: React.FC<ShowFileProps> = ({ path, tall = false }) => {
    const session = useAppSelector((state) => state.session.data);
    const config = useAppSelector((state) => state.session.config);
    const [content, setContent] = useState('');

    const maxHeight = tall ? '400px' : '200px';

    useEffect(() => {
        if (!session?._id || !path) return;

        axios
            .get(`${config.apihost}/download/${session._id}/token`)
            .then((res) => {
                const shortLivedJWT = res.data;
                return axios.get(`${config.apihost}/download/${session._id}/${path}?token=${shortLivedJWT}`);
            })
            .then((res) => {
                // data from the BE will have newlines which informs indentation in the frontend
                setContent(convert.toHtml(res.data));
            })
            .catch((err) => {
                console.error(err);
            });
    }, [session?._id, config.apihost, path]);

    return (
        <pre
            className="m-0 overflow-auto p-[10px] rounded-[5px]"
            style={{
                backgroundColor: '#333',
                color: 'white',
                maxHeight,
                height: maxHeight,
            }}
            dangerouslySetInnerHTML={{ __html: content }}
        />
    );
};

export default ShowFile;

// ui/src/components/showfile.vue
<template>
    <pre :style="{ maxHeight, height }" v-html="content" />
</template>

<script lang="ts">
// @ts-ignore
import Convert from 'ansi-to-html';
const convert = new Convert();

import { mapState } from 'vuex';
import { defineComponent } from 'vue';
import axios from '../axios.instance';

export default defineComponent({
    props: {
        path: String,
        tall: {
            type: Boolean,
            default: false,
        },
    },

    data() {
        return {
            content: '',
            maxHeight: '200px',
            height: '200px',
        };
    },

    computed: {
        ...mapState(['session', 'config']),
    },

    mounted() {
        axios
            .get(`${this.config.apihost}/download/${this.session._id}/token`)
            .then((res) => {
                const shortLivedJWT = res.data;
                return axios.get(
                    `${this.config.apihost}/download/${this.session._id}/${this.path}?token=${shortLivedJWT}`
                );
            })
            .then((res) => {
                const text = JSON.stringify(res.data, undefined, 4);
                this.content = convert.toHtml(text);
                // data from the BE will have newlines which informs indentation in the frontend
                this.content = convert.toHtml(res.data);
            })
            .catch((err) => {
                console.error(err);
            });

        if (this.tall) {
            this.maxHeight = '400px';
            this.height = '400px';
        }
    },
});
</script>
<style scoped>
pre {
    background-color: #333;
    color: white;
    margin: 0;
    overflow: auto;
    padding: 10px;
    border-radius: 5px;
}
</style>
