// ui/src/Participant.vue
<template>
<div style="padding: 20px">
    <p>You can store metadata/phenotypical data for each subject/participants on this datasets in the BIDS dataset.</p>
    <p>Please skip this step if you do not need to store any phenotypical data.</p>
    <h5>Phenotype Columns</h5>
    <small>Define phenotypical keys stored for this study (optional).</small>
    <br><br>
    <el-form>
        <div v-for="(column, key) in ezbids.participantsColumn" :key="key" class="columnEditor">
            <span style="float: right">
                <el-button type="danger" @click="remove(key)" size="mini"><Remove style="width: 16px;"/></el-button>
            </span>
            <b>{{key}}</b>
            <br>
            <br clear="both">
            <el-form-item label="Long Name">
                <el-input placeholder="LongName" v-model="column.LongName" size="mini"/>
            </el-form-item>
            <el-form-item label="Units">
                <el-input placeholder="Units" v-model="column.Units" size="mini"/>
            </el-form-item>
            <el-form-item label="Description">
                <el-input type="textarea" placeholder="Description" v-model="column.Description" size="mini"/>
            </el-form-item>
            <el-form-item label="Options">
                <small>TODO.. (levels)</small>
            </el-form-item>
        </div>
        <p class="columnEditor" style="width: 200px;">
            <el-input placeholder="Add New Column" v-model="newcolumn" size="mini">
                <template #append>
                    <el-button @click="addNewColumn" type="primary">Add</el-button>
                </template>
            </el-input>
        </p>

    </el-form>

    <br clear="both">

    <h5>phenotype.tsv</h5>
    <small>Enter phenotypical data associated with each participants.</small>
    <br><br>
    <div style="width: 100%">
        <table class="phenotype">
        <thead>
        <tr>
            <th>Subject</th>
            <th v-for="(column, key) in ezbids.participantsColumn" :key="key">
                {{key}}
            </th>
        </tr>
        </thead>
        <tbody>
            <tr v-for="(sub) in finalSubs" :key="sub">
                <th>{{sub}}</th>
                <td v-for="(column, key) in ezbids.participantsColumn" :key="key">
                    <el-input v-model.trim="ezbids.participantsInfo[sub][key]" size="mini"/>
                </td>
            </tr>
        </tbody>
        </table>
    </div>
</div>
</template>

<script lang="ts">

import { mapState } from 'vuex'
import { defineComponent } from 'vue'

import { OrganizedSubject } from './store'

//element-plus icons are bad .. replace it with fontawesome
// @ts-ignore
import { Remove } from '@element-plus/icons/lib'

export default defineComponent({
    components: {
        Remove,
    },

    data() {
        return {
            newcolumn: "",
        }
    },

    computed: {
        ...mapState(['ezbids', 'config']),
        //...mapGetters(['findSubjectFromString']),

        finalSubs() {
            let finalSubs = [] as string[]
            this.ezbids._organized.forEach((sub: OrganizedSubject)=>{
                let use = false;
                sub.sess.forEach(ses=>{
                    if(ses.objects.some(o=>!o._exclude)) use = true;
                });
                if(use) finalSubs.push(sub.sub);
            })
            return finalSubs;
        }
    },

    created() {
        //initialize
        this.ezbids._organized.forEach((o:OrganizedSubject)=>{
            if(!this.ezbids.participantsInfo[o.sub]) this.ezbids.participantsInfo[o.sub] = {};
        });
    },

    methods: {
        addNewColumn() {
            if(!this.newcolumn) return;
            this.ezbids.participantsColumn[this.newcolumn] = {
                LongName: "",
                Description: "",
                Units: "",
                Levels: {},
            }
            this.newcolumn = "";
        },


        remove(key: string|number|symbol) {
            delete this.ezbids.participantsColumn[key];
        },

        //TODO
        validate() {
            console.log("todo - validate participant");
        },

        isValid(cb: (v?: string)=>void) {
            this.validate();
            cb();
        }
    },
});
</script>

<style lang="scss" scoped>
.columnEditor {
    background-color: #f9f9f9;
    margin-bottom: 10px;
    padding: 15px;
    border-radius: 5px;
    width: 300px;
    float: left;
    margin-right: 10px;
    margin-bottom: 10px;
    margin-top: 0;
}
table.phenotype {
    width: 100%;
    border-collapse: collapse;
    font-size: 90%;
}
table.phenotype thead {
    background-color: #eee;
    color: #666;
}
table.phenotype td,
table.phenotype th {
    padding: 5px 10px;
}
</style>

// ui/src/pages/convert/Participant.tsx
import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useState } from 'react';
import { useAppSelector } from '../../store/hooks';
import type { OrganizedSubject } from '../../store/slices/ezbidsSlice';

interface ParticipantHandle {
    isValid: (cb: (err?: string) => void) => void;
}

const Participant = forwardRef<ParticipantHandle>(function Participant(_props, ref) {
    const ezbids = useAppSelector((s) => s.ezbids.data);
    const [newcolumn, setNewcolumn] = useState('');
    const [, forceUpdate] = useState(0);

    // Initialize participantsInfo for each organized subject
    useEffect(() => {
        ezbids._organized.forEach((o: OrganizedSubject) => {
            if (!ezbids.participantsInfo[o.subject_idx]) {
                ezbids.participantsInfo[o.subject_idx] = {};
            }
        });
    }, []);

    useImperativeHandle(
        ref,
        () => ({
            isValid(cb: (err?: string) => void) {
                console.log('todo - validate participant');
                cb();
            },
        }),
        []
    );

    // Only show subjects that are really used (not excluded)
    const finalSubs = useMemo(() => {
        const result: number[] = [];
        ezbids._organized.forEach((sub: OrganizedSubject) => {
            let use = false;
            sub.sess.forEach((ses) => {
                if (ses.objects.some((o) => !o._exclude)) use = true;
            });
            if (use) result.push(sub.subject_idx);
        });
        return result;
    }, [ezbids._organized]);

    const addNewColumn = useCallback(() => {
        if (!newcolumn) return;
        if (ezbids.participantsColumn && ezbids.participantsColumn[newcolumn]) return;
        ezbids.participantsColumn[newcolumn] = {
            Description: '',
            Units: '',
            Levels: {},
        };
        setNewcolumn('');
        forceUpdate((n) => n + 1);
    }, [newcolumn, ezbids.participantsColumn]);

    const removeColumn = useCallback(
        (key: string) => {
            delete ezbids.participantsColumn[key];
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsColumn]
    );

    const handleColumnDescriptionChange = useCallback(
        (key: string, value: string) => {
            ezbids.participantsColumn[key].Description = value;
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsColumn]
    );

    const handleColumnUnitsChange = useCallback(
        (key: string, value: string) => {
            ezbids.participantsColumn[key].Units = value;
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsColumn]
    );

    const handleParticipantInfoChange = useCallback(
        (subjectIdx: number, key: string, value: string) => {
            if (!ezbids.participantsInfo[subjectIdx]) {
                ezbids.participantsInfo[subjectIdx] = {};
            }
            ezbids.participantsInfo[subjectIdx][key] = value.trim();
            forceUpdate((n) => n + 1);
        },
        [ezbids.participantsInfo]
    );

    const columnKeys = Object.keys(ezbids.participantsColumn || {});

    return (
        <div className="p-5">
            <p>You can store metadata/phenotypical data for each participant in this dataset.</p>
            <p>Please skip this step if you do not wish to store any phenotypical data.</p>

            <h5 className="text-base font-semibold mt-4">Phenotype Columns</h5>
            <small className="text-gray-500">Define phenotypical keys stored for this study (recommended).</small>
            <br />
            <br />

            <div className="flex flex-wrap gap-2.5">
                {/* Column Editors */}
                {columnKeys.map((key) => {
                    const column = ezbids.participantsColumn[key];
                    return (
                        <div key={key} className="bg-gray-50 mb-2.5 p-4 rounded w-[300px] text-center">
                            <span className="float-right">
                                <button
                                    className="px-2 py-0.5 bg-red-500 hover:bg-red-600 text-white text-xs rounded"
                                    onClick={() => removeColumn(key)}
                                >
                                    &#10005;
                                </button>
                            </span>
                            <b>{key}</b>
                            <br />
                            <br className="clear-both" />

                            <div className="mb-2 text-left">
                                <label className="block text-sm text-gray-600 mb-1">Description</label>
                                <textarea
                                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    placeholder="Description"
                                    value={column.Description || ''}
                                    onChange={(e) => handleColumnDescriptionChange(key, e.target.value)}
                                />
                            </div>

                            <div className="mb-2 text-left">
                                <label className="block text-sm text-gray-600 mb-1">Units</label>
                                <input
                                    type="text"
                                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    placeholder="Units"
                                    value={column.Units || ''}
                                    onChange={(e) => handleColumnUnitsChange(key, e.target.value)}
                                />
                            </div>

                            <div className="mb-2 text-left">
                                <label className="block text-sm text-gray-600 mb-1">Levels</label>
                                <small className="text-gray-400">TODO.. (levels)</small>
                            </div>
                        </div>
                    );
                })}

                {/* Add New Column */}
                <div className="bg-gray-50 p-4 rounded w-[200px] text-center">
                    <div className="flex">
                        <input
                            type="text"
                            className="border border-gray-300 rounded-l px-2 py-1 text-sm flex-1 min-w-0"
                            placeholder="Add New Column"
                            value={newcolumn}
                            onChange={(e) => setNewcolumn(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === 'Enter') addNewColumn();
                            }}
                        />
                        <button
                            className="px-3 py-1 bg-blue-500 hover:bg-blue-600 text-white text-sm rounded-r"
                            onClick={addNewColumn}
                        >
                            Add
                        </button>
                    </div>
                    <div className="mt-2">
                        <a
                            href="https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file"
                            target="_blank"
                            rel="noreferrer"
                            className="text-blue-500 text-sm"
                        >
                            See here for suggestions
                        </a>
                    </div>
                </div>
            </div>

            <br className="clear-both" />

            <h5 className="text-base font-semibold mt-4">participants.tsv</h5>
            <small className="text-gray-500">Enter phenotypical data associated with each participant.</small>
            <br />
            <br />

            <div className="w-full overflow-x-auto">
                <table className="w-full border-collapse text-[90%]">
                    <thead className="bg-gray-100 text-gray-600">
                        <tr>
                            <th className="p-1.5 px-2.5 text-left">participant_id</th>
                            {columnKeys.map((key) => (
                                <th key={key} className="p-1.5 px-2.5 text-left">
                                    {key}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {finalSubs.map((subjectIdx) => (
                            <tr key={subjectIdx}>
                                <th className="p-1.5 px-2.5 text-left font-normal">
                                    sub-{ezbids.subjects[subjectIdx]?.subject}
                                </th>
                                {columnKeys.map((key) => (
                                    <td key={key} className="p-1.5 px-2.5">
                                        <input
                                            type="text"
                                            className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                            value={ezbids.participantsInfo[subjectIdx]?.[key] || ''}
                                            onChange={(e) =>
                                                handleParticipantInfoChange(subjectIdx, key, e.target.value)
                                            }
                                        />
                                    </td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
});

export default Participant;
